/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-09-02 07:36:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.entity.ProductDtls;
import com.DAO.ProductDAOImpl;
import com.DB.DBConnect;
import com.entity.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/New%20folder/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Revpro_App/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/all_component/navbar.jsp", Long.valueOf(1725174711747L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1723702673464L));
    _jspx_dependants.put("/all_component/allcss.jsp", Long.valueOf(1723742202781L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.entity.User");
    _jspx_imports_classes.add("com.DAO.ProductDAOImpl");
    _jspx_imports_classes.add("com.entity.ProductDtls");
    _jspx_imports_classes.add("com.DB.DBConnect");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Dairy Products</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("	\r\n");
      out.write("<link rel=\"stylesheet\" href=\"all_component/style.css\">");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	padding-bottom: 60px; /* Ensure there's space for the footer */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("	position: fixed; /* Fixed at the bottom of the viewport */\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: #198754; /* Background color */\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 10px 0;\r\n");
      out.write("	visibility: hidden; /* Initially hidden */\r\n");
      out.write("	opacity: 0; /* Initially transparent */\r\n");
      out.write("	transition: visibility 0s, opacity 0.5s ease-in-out;\r\n");
      out.write("	/* Smooth transition */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-section {\r\n");
      out.write("	margin: 30px 0; /* Adding some margin to the top and bottom */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card {\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	padding: 20px; /* Increased padding for a more spacious feel */\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	background-color: #fff; /* Slightly different background color */\r\n");
      out.write("	border-radius: 15px; /* Rounded corners */\r\n");
      out.write("	box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1); /* Enhanced shadow */\r\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card:hover {\r\n");
      out.write("	transform: translateY(-5px); /* Subtle lift effect on hover */\r\n");
      out.write("	box-shadow: 0 12px 24px rgba(0, 0, 0, 0.2);\r\n");
      out.write("	/* More pronounced shadow */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card img {\r\n");
      out.write("	height: 100px; /* Set a fixed height */\r\n");
      out.write("	width: 20%; /* Ensure the image spans the width of its container */\r\n");
      out.write("	object-fit: cover; /* Maintain aspect ratio and cover the container */\r\n");
      out.write("	border-radius: 10px; /* Rounded corners for the image */\r\n");
      out.write("	margin-bottom: 15px; /* Space below the image */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card p {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	font-weight: bold; /* Making the product names bolder */\r\n");
      out.write("	color: #333; /* Darker text for better readability */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card .price {\r\n");
      out.write("	font-size: 1.4em; /* Slightly larger font size */\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #28a745;\r\n");
      out.write("	margin-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card button {\r\n");
      out.write("	background-color: #007bff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 12px 25px; /* Increased padding for a larger button */\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card button:hover {\r\n");
      out.write("	background-color: #0056b3;\r\n");
      out.write("	transform: scale(1.05); /* Slightly enlarges the button on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-all-button {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 30px; /* Increased margin for better separation */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-all-button button {\r\n");
      out.write("	background-color: #007bff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 12px 25px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".view-all-button button:hover {\r\n");
      out.write("	background-color: #0056b3;\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	User u = (User) session.getAttribute("userobj");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- First Navbar -->\r\n");
      out.write("<div class=\"container-fluid p-3\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<!-- Left side with \"Dairy\" text -->\r\n");
      out.write("		<div class=\"col-md-3\">\r\n");
      out.write("			<h3>Dairy</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Centered search form -->\r\n");
      out.write("		<div class=\"col-md-6\">\r\n");
      out.write("			<form class=\"form-inline my-2 my-lg-0 d-flex justify-content-center\"\r\n");
      out.write("				action=\"search.jsp\" method=\"post\">\r\n");
      out.write("				<input class=\"form-control mr-sm-2\" type=\"search\" name=\"ch\"\r\n");
      out.write("					placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("				<button class=\"btn btn-primary my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Right-side login/register/logout buttons -->\r\n");
      out.write("		<div class=\"col-md-3 d-flex justify-content-end\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Second Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-custom\">\r\n");
      out.write("	<a class=\"navbar-brand\" href=\"#\"><i class=\"fa-solid fa-house\"></i></a>\r\n");
      out.write("	<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("		data-target=\"#navbarSupportedContent\"\r\n");
      out.write("		aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("		aria-label=\"Toggle navigation\">\r\n");
      out.write("		<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("	</button>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("		<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\" href=\"index.jsp\">Home\r\n");
      out.write("					<span class=\"sr-only\">(current)</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"nav-item dropdown\"><a\r\n");
      out.write("				class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\r\n");
      out.write("				data-toggle=\"dropdown\" aria-expanded=\"false\"> Products </a>\r\n");
      out.write("				<div class=\"dropdown-menu\">\r\n");
      out.write("					<a class=\"dropdown-item\" href=\"all_milkproduct.jsp\">Milk</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_paneer.jsp\">Paneer</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_ghee.jsp\">Ghee</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_curd.jsp\">Curd</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_icecream.jsp\">Ice Cream</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_milkshakes.jsp\">Milk Shake</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_lassi.jsp\">Lassi</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_icebars.jsp\">Ice Bars</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_cheese.jsp\">Cheese</a> <a\r\n");
      out.write("						class=\"dropdown-item\" href=\"all_others.jsp\">Others</a>\r\n");
      out.write("				</div></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("			<a href=\"settings.jsp\" class=\"btn btn-light my-2 my-sm-0\" type=\"submit\">Setting</a>\r\n");
      out.write("			<a href=\"contact.jsp\" class=\"btn btn-light my-2 my-sm-0 ml-2\" type=\"submit\">Contact\r\n");
      out.write("				Us</a>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	function confirmLogout() {\r\n");
      out.write("		if (confirm(\"Are you sure you want to log out?\")) {\r\n");
      out.write("			document.getElementById(\"logoutForm\").submit();\r\n");
      out.write("		}\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<div\r\n");
      out.write("    id=\"carouselAutoplaying\"\r\n");
      out.write("    class=\"carousel slide carousel-dark mt-3 mb-3\"\r\n");
      out.write("    data-bs-ride=\"carousel\"\r\n");
      out.write("    data-bs-interval=\"3000\"\r\n");
      out.write("    data-bs-pause=\"false\"\r\n");
      out.write("  >\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"carousel-item active\">\r\n");
      out.write("        <img src=\"img/b1.jpg\" class=\"d-block w-100\" alt=\"Slide 1\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"img/b2.jpg\" class=\"d-block w-100\" alt=\"Slide 2\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"img/b3.jpg\" class=\"d-block w-100\" alt=\"Slide 3\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"carousel-item\">\r\n");
      out.write("        <img src=\"img/b4.jpg\" class=\"d-block w-100\" alt=\"Slide 4\" />\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button\r\n");
      out.write("      class=\"carousel-control-prev\"\r\n");
      out.write("      type=\"button\"\r\n");
      out.write("      data-bs-target=\"#carouselAutoplaying\"\r\n");
      out.write("      data-bs-slide=\"prev\"\r\n");
      out.write("    >\r\n");
      out.write("      <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button\r\n");
      out.write("      class=\"carousel-control-next\"\r\n");
      out.write("      type=\"button\"\r\n");
      out.write("      data-bs-target=\"#carouselAutoplaying\"\r\n");
      out.write("      data-bs-slide=\"next\"\r\n");
      out.write("    >\r\n");
      out.write("      <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("	 \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"row bg-success text-center p-5 text-white border-bottom shadow\">\r\n");
      out.write("			<h1>Products</h1>\r\n");
      out.write("			<small class=\"fs-5\">We have adopted a Corporate Social\r\n");
      out.write("				Responsibility (“CSR”) policy in compliance with the requirements of\r\n");
      out.write("				the Companies Act, 2013 and the rules framed there under. Our CSR\r\n");
      out.write("				activities are primarily focused on initiatives related to education\r\n");
      out.write("				and these activities are centered around the geographical areas near\r\n");
      out.write("				our processing plants.</small>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2 class=\"text-center\">Welcome To Our Dairy Products</h2>\r\n");
      out.write("		<h3 class=\"text-center\">.....Eat Healthy Stay Healthy.....</h3>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Milk Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> milkList = dao.getMilkProduct();
				for (ProductDtls b : milkList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_milkproduct.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Paneer Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Paneer Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao2 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> paneerList = dao2.getPaneerProduct();
				for (ProductDtls b : paneerList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_paneer.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Ghee Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Ghee Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao3 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> gheeList = dao3.getGheeProduct();
				for (ProductDtls b : gheeList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_ghee.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Curd Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Curd Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao4 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> curdList = dao4.getCurdProduct();
				for (ProductDtls b : curdList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_curd.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Ice Creams Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Ice Creams</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao5 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> iceCreamList = dao5.getIceCreamProduct();
				for (ProductDtls b : iceCreamList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_icecream.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Milk Shake Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Milk Shakes</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao6 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> milkShakeList = dao6.getMilkShakeProduct();
				for (ProductDtls b : milkShakeList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_milkshakes.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Lassi Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Lassi Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao7 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> lassiList = dao7.getLassiProduct();
				for (ProductDtls b : lassiList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_lassi.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Ice Bars Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Ice Bars</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao8 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> iceBarList = dao8.getIceBarProduct();
				for (ProductDtls b : iceBarList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_icebars.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Cheese Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Cheese Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao9 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> cheeseList = dao9.getCheeseProduct();
				for (ProductDtls b : cheeseList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_cheese.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<!-- Other Products Section -->\r\n");
      out.write("		<section class=\"product-section\">\r\n");
      out.write("			<h2 class=\"text-center\">Other Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				ProductDAOImpl dao0 = new ProductDAOImpl(DBConnect.getConn());
				List<ProductDtls> othersList = dao0.getOtherProduct();
				for (ProductDtls b : othersList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"product-card\">\r\n");
      out.write("						<img src=\"products/");
      out.print(b.getPhotoName());
      out.write("\"\r\n");
      out.write("							style=\"width: 150px; height: 200px;\"\r\n");
      out.write("							class=\"img-responsive center-block\" alt=\"");
      out.print(b.getProductName());
      out.write("\">\r\n");
      out.write("						<p>");
      out.print(b.getProductName());
      out.write("</p>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Rs.");
      out.print(b.getPrice());
      out.write("/-\r\n");
      out.write("						</p>\r\n");
      out.write("						<a href=\"view_products.jsp?pid=");
      out.print(b.getProductId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-primary btn-sm ml-2\">Details</a>\r\n");
      out.write("						");

						if (u == null) {
						
      out.write("\r\n");
      out.write("						<a href=\"login.jsp\" class=\"btn btn-danger btn-sm ml-2\">Add to\r\n");
      out.write("							Cart</a> <a href=\"login.jsp\" class=\"btn btn-success btn-sm ml-2\">Add\r\n");
      out.write("							to Wishlist</a>\r\n");
      out.write("						");

						} else {
						
      out.write("\r\n");
      out.write("						<a href=\"cart?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-danger btn-sm ml-2\">Add to Cart</a> <a\r\n");
      out.write("							href=\"wishlist?pid=");
      out.print(b.getProductId());
      out.write("&&uid=");
      out.print(u.getId());
      out.write("\"\r\n");
      out.write("							class=\"btn btn-success btn-sm ml-2\">Add to Wishlist</a>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"view-all-button\">\r\n");
      out.write("				<a href=\"all_others.jsp\">\r\n");
      out.write("					<button>View All</button>\r\n");
      out.write("				</a>\r\n");
      out.write("		</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /all_component/navbar.jsp(27,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<a href=\"login.jsp\" class=\"btn btn-success ml-2\">Login</a>\r\n");
          out.write("				<a href=\"register.jsp\" class=\"btn btn-primary ml-2\">Register</a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /all_component/navbar.jsp(31,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userobj}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<a href=\"checkout.jsp\" class=\"btn ml-2\"\r\n");
          out.write("					style=\"font-size: 1rem; color: black; text-decoration: none;\">\r\n");
          out.write("					<i class=\"fas fa-cart-shopping\"></i>\r\n");
          out.write("				</a>\r\n");
          out.write("				<a href=\"wishlist.jsp\" class=\"btn ml-2\"\r\n");
          out.write("					style=\"font-size: 1rem; color: red; text-decoration: none;\"> <i\r\n");
          out.write("					class=\"fas fa-heart\"></i>\r\n");
          out.write("				</a>\r\n");
          out.write("				<a href=\"login.jsp\" class=\"btn btn-success ml-2\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userobj.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("				<a href=\"logout\" class=\"btn btn-success ml-2\">Logout</a>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
